config/routes.rb
Rails.application.routes.draw do

  resources :images

  resources :news

  # set a route to match the hackathon form

  get "/other_events" => redirect("https://docs.google.com/forms/d/1DS7oHuNCYChtcR0WMxuogjYcXEkBCbkeKKf-l4VAfzQ/edit?ts=583e546b"), :as => :other_events
  get "/victor" => redirect("https://icancodeclub.mypaysimple.com/s/icancode-club-school-courses"), :as => :victor
  get "/hackathon" => redirect("https://docs.google.com/forms/d/e/1FAIpQLSd8cA-Oa_p7nbt9TkwZtP7ijqbp5VFgervPen1IqaF1qXox_Q/viewform?c=0&w=1"), :as => :hackathon
  resources :contents
  
  resources :courses

  #resources :students

  devise_for :users

  get 'resources/dragdrop'

  get 'resources/completetag'

  get 'resources/editor'

  post 'resources/download'

  get 'home' => 'page#home'
  get 'jcc' => 'page#jcc'

  get 'curriculum' => 'page#curriculum'

  get 'contact', to: 'messages#new', as: 'contact'
  post 'contact', to: 'messages#create'

  get 'courses_overview' => 'page#courses'

  get 'academic' => 'page#academic'

  get 'camps' => 'page#camps'
  get 'summer' => 'page#summer'
  get 'events' => 'page#events'

  get 'dashboard' => 'dashboard#index'

  get 'admin' => 'dashboard#admin'

  root 'page#home'
end

app/models/class_day.rb
class ClassDay < ActiveRecord::Base
  has_many :students

end

app/models/classtime.rb
class Classtime < ActiveRecord::Base

  TIMES = ['1:00','1:30','2:00','2:30','3:00','3:30','4:00','4:30','5:00','5:30','6:00','6:30','7:00']

  belongs_to :course
  belongs_to :weekday
  has_many :course_students
end

app/models/content.rb
class Content < ActiveRecord::Base
end

app/models/course.rb
class Course < ActiveRecord::Base

  YEARS = []
  6.times do |yearcount|
    YEARS << Time.now.year + yearcount
  end
  #this allows the user to select the year when the course is available.  it looks 6 years into the future for planning purposes.  if nil, the course is offered every year


  monetize :price_cents #allow this column to hold prices

  belongs_to :course_type #difines if class is summer, school, vacation, etc.
  has_many :classtimes #has an array of all possible classtimes

  has_many :students, :through => :course_students #list of students in this course
  has_many :course_students

  accepts_nested_attributes_for :classtimes, :reject_if => :all_blank, :allow_destroy => true

  validates :name, :code, :course_type_id, :presence => true

end

app/models/course_student.rb
class CourseStudent < ActiveRecord::Base
  belongs_to :student
  belongs_to :course
  belongs_to :classtime
end

app/models/course_type.rb
class CourseType < ActiveRecord::Base
  has_many :courses
end

app/models/image.rb
class Image < ActiveRecord::Base
  has_attached_file :file, styles: {large: "1400x"}
  validates_attachment_content_type :file, content_type: /\Aimage\/.*\Z/
end

app/models/message.rb
class Message

  include ActiveModel::Model
  include ActiveModel::Conversion
  include ActiveModel::Validations

  attr_accessor :name, :email, :content, :phone_number, :referral

  validates :name,
            presence: true

  validates :email,
            presence: true

  validates :content,
            presence: true

end

app/models/news.rb
class News < ActiveRecord::Base
end

app/models/student.rb
class Student < ActiveRecord::Base

  GENDERS = ["Male", "Female", "Other"]


  belongs_to :user
  belongs_to :class_day
  belongs_to :class_time

  has_many :courses, :through => :course_students
  has_many :course_students

  has_many :student_parent_informations, :dependent => :destroy
  accepts_nested_attributes_for :student_parent_informations, :allow_destroy => true

  validates :firstname, :lastname, :birthday, :user_id,
      presence: true

  validate :require_parents

  #TODO: validate everything


  #function to set the user

  def set_user!(user)
    self.user_id = user.id
    self.save!
  end

  private

  def require_parents
    errors.add(:base, "You must provide at least one parent.") if student_parent_informations.size < 1 #TODO: validate when deleting with JS
  end


end

app/models/user.rb
class User < ActiveRecord::Base

  attr_accessor :login

  has_many :students

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions.to_h).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    else
      where(conditions.to_h).first
    end
  end

end

app/models/weekday.rb
class Weekday < ActiveRecord::Base
  has_many :classtimes
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/contents_helper.rb
module ContentsHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/news_helper.rb
module NewsHelper

end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>iCanCodeClub</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
	<!--[if lt IE 8]>
<script src="http://ie7-js.googlecode.com/svn/version/2.1(beta4)/IE8.js"></script>
<![endif]-->
	
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

<!--[if !IE 8]><!-->
<%= javascript_include_tag "jquery.waypoints.min.js" %>
<%= javascript_include_tag "prism.js" %>
<%= javascript_include_tag "header.js" %>
	<!--<![endif]-->

<!--[if lt IE 8]>
<%= javascript_include_tag "header.js" %>
<![endif]-->


  <%= csrf_meta_tags %>

  <link href='http://fonts.googleapis.com/css?family=Sniglet:400,800|Varela+Round' rel='stylesheet' type='text/css'>

  <%= stylesheet_link_tag 'http://fonts.googleapis.com/css?family=Roboto:400,300,100|Roboto+Slab', media: 'all' %>
  <%= stylesheet_link_tag 'http://fonts.googleapis.com/css?family=Varela+Round', media: 'all' %>

  <link href='http://fonts.googleapis.com/css?family=Merriweather:400,300' rel='stylesheet' type='text/css'>
  <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- google analytics -->

    <script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');
    ga('create', 'UA-63963915-2', 'auto');
    ga('send', 'pageview');
    </script>



</head>
<% if controller.controller_name == 'news' %>
    <body data-no-turbolink>
<% else %>
    <body >
<% end %>
<!-- header -->
<header>

  <!--nav goes here-->
  <nav>
    <%= link_to root_path do %>
        <%= image_tag('icc_head.png', width: '150px', height: '37px', id: 'logo') %>
    <% end %>
    <p id="absohead" class="nomobile"><span style="color:black;font-weight: 600;">Learning Center</span><br>A Fun Digital Sandbox<br>for Lifelong
      Computing!</p>

    <div class="navContainer nav1">
      <%= render "page/links" %>
    </div>

    <div class="navContainer nav2">
      <div class="hotdog">
        MENU
      </div>
      <div class="floatmenu">
        <%= render "page/links" %>
      </div>

    </div>

  </nav>
  <!--
  <div id="navLogin">
    <% # link_to('Login', controller: 'page', action: 'home') %>
  </div>
-->
</header>
<div style="height: 60px;"></div>

<% if !notice.nil? and !current_page?(:action => 'home', :controller => 'page') and !current_page?('/') %>
    <p id="notice"><%= notice %></p>
<% end %>

<!--<div id="push"></div>-->
<%= yield %>
<hr>
<footer class="wow popUp">
  <div class="container_wide">

    <div class="col-third">
      <div class="content">
        <h1>Contact Us</h1>
        <hr>
        <p>
          <%= mail_to 'info@icancodeclub.com' %><br>
          Phone: (585) 434-5533
        </p>
      </div>
    </div>
    <div class="col-third">
      <div class="content">
        <h1>Social Media</h1>
        <hr>
        <p>
          <%= link_to 'https://www.facebook.com/pages/ICanCode/942981635784038' do %>
              <%= image_tag 'facebook.png', width: 40, height: 40 %>
          <% end %>
	  <%= link_to 'https://twitter.com/iCanCodeClub' do %>
              <%= image_tag 'twitter.png', width: 40, height: 40 %>
          <% end %>

          <%= link_to 'https://www.linkedin.com/pub/icancode-kids-club/101/9b7/6b1' do %>
              <%= image_tag 'linked-in.png', width: 40, height: 40 %>
          <% end %>
        </p>
      </div>
    </div>
    <div class="col-third">
      <div class="content">
        <h1>More</h1>
        <hr>
	<p>Proud Partner with
	</br>
	<%= image_tag 'pcc.jpg' %>
  <%= image_tag 'brighton.jpg' %>
	</p>

      </div>
    </div>
  </div>
</footer>
<div id="cr" class="wow copyslide">
  &copy; iCanCodeClub <%= Date.today.year %>
</div>
</body>
</html>

app/views/page/_courseHeader.html.erb
<div style="background: url(<%= background_url %>) no-repeat center center" class="courseHeader fbg" >
  <h1 class="wow popUp"><%= title %></h1>

  <div class="break"></div>
  <div class="row textCenter">
    <% if links %>
        <a href="#beginner">
          <div class="homeButton f_blue">BEGINNER</div>
        </a>
        <a href="#intermediate">
          <div class="homeButton f_green">INTERMEDIATE</div>
        </a>
        <a href="#advanced">
          <div class="homeButton">ADVANCED</div>
        </a><br>
    <% end %>
    <a href="#allCourses">
      <div class="homeButton f_white">ALL PROGRAMS</div>
    </a>
  </div>
</div>

app/views/page/_courses.html.erb
<div class="rowbig" id="allCourses">
  <div class="content">
    <div id="lessonWrapper">
      <div class="col-third lesson" id="program-a">
        <h1>Schools and Clubs</h1>
        <hr>
        <%= image_tag("icon_programming_p.png") %>
        <%=link_to academic_path do%>
            <div class="button wow popUp">
              <div>
                Visit Page
              </div>
            </div>
        <% end %>
        <p>Offers programming focused courses at your school, Community Center, and other Pop Up locations.</p>
      </div>
      <div class="col-third lesson" id="program-b">
        <h1>Coding Camps</h1>
        <hr>
        <%= image_tag("icon_web.png") %>
        <%=link_to camps_path do%>
            <div class="button wow popUp">
              <div>
                Visit Page
              </div>
            </div>
        <% end %>
        <p>During school closures and Holidays.</p>
      </div>
      <div class="col-third lesson" id="program-c">
        <h1>Workshops & Events</h1>
        <hr>
        <%= image_tag("icon_app.png") %>
        <%=link_to events_path do%>
            <div class="button wow popUp">
              <div>
                Visit Page
              </div>
            </div>
        <% end %>
        <p>Workshops, Hackathons, Robotics Events, Tech Tours, Special Events, and more.</p>  <!--TODO: get actual descriptions-->
      </div>
    </div>
  </div>
</div>

app/views/page/_links.html.erb
<div class="navLeft">
  <%=link_to('HOME', home_path)%>
</div>
<div class="navLeft">
  <%= link_to('ENROLL',courses_overview_path) %>
</div>
<div class="navLeft">
  <%=link_to('CONTACT US', contact_path, {:style => 'color: #f271b6'})%>
</div>

<% if user_signed_in? %>
  <% if current_user.admin %>
    <div class="navLeft">
      <%=link_to('DASHBOARD', dashboard_path)%>
    </div>
  <% end %>
<% else %>
    <!--<div class="navLeft">  temp disabled
      <%#=link_to('SIGN IN', new_user_session_path)%>
    </div>-->
<% end %>

app/views/page/academic.html.erb
<style>
a{
    font-size: 125%;
}
</style>

<div class="lessonPage programming"> <!--used for css rules -->
  <%= render "page/courseHeader", title: 'Academic Year Program', links: false, background_url: asset_url( 'academic_background.jpg') %>

  <div class="break"></div>

  <p style="margin: 0 auto; padding: 24px; display: block; text-align: center; font-size: 24px; font-weight: bold;">Want us to come to your school? <%= link_to "Contact us Here", "mailto:info@icancodeclub.com?subject=Request%20to%20Start%20a%20Coding%20Club%20at%20School" %></p>

  <div class="container_wide">
    <div class="content">
      <div class="colContainer">
        <div class="leftCol">
          <h5 class="f_blue">What We Teach</h5>
        </div>
        <div class="rightCol">
          <div class="horizline f_blue"></div>
          <p>
            &#8226;We teach 21st Century skills needed to succeed in this innovative economy using MIT’s Scratch block based programming in addition to JAVA, Minecraft, JavaScript, HTML, CSS, Unity C#, 3d Modeling, Arduino and VEX Robotics.<br>
&#8226;Students learn by Doing! Students learn programming by creating their own interactive stories, games, animations, apps, websites, and by building their own Robots<br>

&#8226;Students follow a project based curriculum using a combination of instructor-led and self-guided formats based on skills (beginner, intermediate, advanced). <br>

&#8226;Students are assigned to a coding mentor to ensure student continues to progress into more advanced coding platforms
	        <a href="/curriculum" class="wow popUp">More About Curriculum</a>
        </p>
        </div>
      </div>
    </div>
  </div>

  <div class="container_wide">
    <div class="content">
      <div class="colContainer">
        <div class="leftCol">
          <h5 class="f_blue">How it Works</h5>
        </div>
        <div class="rightCol">
          <div class="horizline f_blue"></div>
          <p>
             • Weekly classes <br>
            • Trained Coding Instructors <br> 
 • Progress reports and prizes <br>
 • School portal, Online curriculum and Remote access from Home <br>
 • Grades 3-10 <br>
 • Low student to teacher ratio <br>
  • Free participation in Special Events, Robotics Events, Tech Tours, Hack Sessions, Expert Series, and Club Hackathons. <br>
• If students miss a class, they can make it up any day of the month based on availability (reservation required). <br>
 • Cool iCanCode Club T-Shirt when your child joins! <br>
 • Can start classes anytime! Schedule your Free Trial TODAY!<br>
          </p>
        </div>
      </div>
    </div>
  </div>

  <div class="container_wide">
    <div class="content">
      <div class="colContainer">
        <div class="leftCol">
          <h5 id="pricing">Which coding platform is best for my Child?</h5>
        </div>
        <div class="rightCol">
          <div class="horizline"></div>
          <p>
            Schedule a FREE TRIAL to find out!  Our professional staff work with families to outline learning goals and select appropriate platforms. Your child will fit right in! </br>
    <br>
    <br>

    <!-- <a href="https://icancodeclub.mvcodeclub.com/semesters/fall-rochester">View Fall Schedules</a> -->
          </p>
        </div>
      </div>
    </div>
  </div>

  <div class="container_wide">
    <div class="content">
      <div class="colContainer">
        <div class="leftCol">
          <h5 class="f_green">Class Schedules and Pricing</h5>
        </div>
        <div class="rightCol">
          <div class="horizline f_green"></div>
<p>

<a style="font-weight: 800; font-size: 20px;" href='https://icancodeclub.mypaysimple.com/s/icancode-club-popup-locations'>Pop Up Location Schedules</a> 
<br>

<a style="font-weight: 800; font-size: 20px;" href='https://icancodeclub.mypaysimple.com/s/icancode-club-school-courses'>School Location Schedules</a> <br>

• Private group classes available for friends, family members, etc, a coding mentor will be assigned to the group (Minimum of 4) <br>

• Girls only classes available (Days and Times Available on demand)<br>
<br>

          </p>
        </div>
      </div>
    </div>
  </div> 

  <!--easy switching between courses-->
  <%= render "page/courses" %>
</div>

app/views/page/camps.html.erb
<div class="lessonPage webDesign"> <!--used for css rules -->
  <%= render "page/courseHeader", title: 'Coding Camps Program', links: false, background_url: asset_url( 'coding_camp_background.jpg')  %>

  <div class="break"></div>
  
  <p style="margin: 0 auto; padding: 24px; display: block; text-align: center; font-size: 24px; font-weight: bold;">Want us to come to your school? <%= link_to "Contact us Here", "mailto:info@icancodeclub.com?subject=Request%20to%20Start%20a%20Coding%20Club%20at%20School" %></p>

  <div class="container_wide">
    <div class="content">
      <div class="colContainer">
        <div class="leftCol">
          <h5>Overview</h5>
        </div>
        <div class="rightCol">
          <div class="horizline"></div>
          <p>
            CODE, PLAY & INNOVATE
            <br><br>
            At iCanCode camps, student learn Cool 21st century programming skills the fun way and enjoy a fun tech experience combined with unplugged activities.<br><br>
            Campers build their own custom games and Websites while experiencing different coding platforms that incorporate math, physics, art and music, while enhancing their logical thinking and problem solving skills. Campers work on custom lesson plans based on age, interest and skill level with qualified coding instructors. Coding platforms include but not limited to SCRATCH INTERACTIVE GAMES & STORIES • Game Design in JAVASCRIPT • JAVA • UNITY 3D • ROBLOX PROGRAMMING in LUA • MINECRAFT MODDING in JAVA • ANIMATIONS•  WEB DEVELOPMENT• HTML• CSS• VEX & ARDUINO ROBOTICS
          </p>
        </div>
      </div>
    </div>
  </div>

  <div class="container_wide">
    <div class="content">
      <div class="colContainer">
        <div class="leftCol">
          <h5>Camp Schedules</h5>
        </div>
        <div class="rightCol">
          <div class="horizline"></div>
          <p>
            During school closures and holidays:
            Full day camps available for everyone, members and non-members.
          </p>
        </div>
      </div>
    </div>
  </div>

 <div class="break"></div>
  <div class="container_wide" id="beginner">
    <div class="content">
      <div class="colContainer">
        <div class="leftCol">
	<div style="width: 100%">
</div>
          <h5>Camps</h5>
        </div>
        <div class="rightCol">

          <div class="horizline"></div>
          <p>
            Full day programs: <br> 

            <a target="_blank" href="https://brightonschools.revtrak.net/">Click here for available schedules and pricing at Brighton</a><br>
            <a target="_blank" href="http://www.perinton.org/">Click here for available schedules and pricing at Perinton</a><br>

            <p style='font-size: 32px;'>Summer Camps in Perinton and Brighton</p>

            <%= image_tag "flyer_perinton.jpg", style: 'float: left; width: 50%;' %>
            <%= image_tag "flyer_brighton.jpg", style: 'float: left; width: 50%;' %>

        </div>
      </div>
    </div>
<br><br>
  </div>

  <!--easy switching between courses-->
  <%= render "page/courses" %>
</div>

app/views/page/courses.html.erb
<div class="container_wide" style='background: white;'>
    <div class="content">
    	<%= image_tag 'icancode_pink.jpg', style: 'width: 50%; margin: 0 auto; display: block; min-width: 400px;' %>
    </div>
</div>

<div class="page" style="padding: 71px 0; background: #3EA8D8;">

    <div class="container_wide">
      <% @courses.each do |course| %>
          <%= course.name %>
      <%end %>
  </div>

  <%= render "page/courses" %>
</div>

app/views/page/events.html.erb
<style>
a{font-size: 125%
}
</style>

<div class="lessonPage gameDesign"> <!--used for css rules -->
  <%= render "page/courseHeader", title: 'Workshops & Events', links: false, background_url: asset_url( 'summer_background.jpg') %>

  <div class="break"></div>

  <p style="margin: 0 auto; padding: 24px; display: block; text-align: center; font-size: 24px; font-weight: bold;">Want us to come to your school? <%= link_to "Contact us Here", "mailto:info@icancodeclub.com?subject=Request%20to%20Start%20a%20Coding%20Club%20at%20School" %></p>

  
  <div class="container_wide" id="beginner">
    <div class="content">
      <div class="colContainer">
        <div class="leftCol">
	<div style="width: 100%">
</div>
          <h5>Workshops and Special Events</h5>
        </div>
        <div class="rightCol">

          <div class="horizline"></div>
          <p>
          Workshops, Hackathons, Robotics Events, Tech Tours, Hack Sessions, Expert Series, and Special Events that are held at iCanCode’s center, libraries, and community events throughout the year.
	
  <br><a href="https://docs.google.com/forms/d/e/1FAIpQLSd8cA-Oa_p7nbt9TkwZtP7ijqbp5VFgervPen1IqaF1qXox_Q/viewform?c=0&w=1">Hackathon Registration</a>
  <br><%= link_to 'Other Events Registration', other_events_path %>

         </p>
        </div>
      </div>
    </div>
  </div>
  <!--easy switching between courses-->
  <%= render "page/courses" %>
</div>

app/views/page/home.html.erb
<div id="backgroundFull" style="background-image: url(' <%= asset_url 'background.jpg' %> ')">
</div>
<div id="backgroundCover">
  <div id="homeText" class="wow popUp">
    <div>
      <%= image_tag "logo_banner.png", class: "bannerHeader" %>
      <h3 class="" style="color: #ffffff;">After School Coding Club</h3>
<h3 class="" style="color: #ffffff;">Grades 3-10</h3>


      <div class="centerHorizontal veloPopUp" id="callButtons">
       
        <a href="#promos">
          <div class="homeButton home">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;PROMOS&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</div>
        </a>
        <a href="#programs">
          <div class="homeButton home">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;PROGRAMS&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</div>
        </a>

        <a href="#about">
          <div class="homeButton home">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;ABOUT&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</div>
        </a>
        <br>

        <a href="https://www.facebook.com/pg/iCanCodeClub/photos/?tab=albums">
          <div style="background: white; color: #53C6D9; width: 100px;" class="homeButton home">GALLERY</div>
        </a>
        <%= link_to events_path do %>
          <div style="background: white; color: #53C6D9; width: 100px;" class="homeButton home">EVENTS</div>
        <% end %>
        <br>

        <a href="mailto:info@icancodeclub.com?subject=Ask%20About%20a%20Free%20Trial">
          <div style="background: white; color: #53C6D9" class="homeButton home">FREE TRIAL</div>
        </a>
	

	<!-- <a href="http://goo.gl/forms/jvQiNVHBxi">
          <div style="background: white; color: #53C6D9" class="homeButton home">&nbsp;&nbsp;&nbsp;&nbsp;EVENTS&nbsp;&nbsp;&nbsp;&nbsp;</div>
        </a> -->


        <!--
        <%= link_to courses_overview_path do %>
            <div class="homeButton home">COURSES</div>
        <% end %>
        -->
      </div>
    </div>
  </div>
</div>

<hr class="thick">
<div class="greyWrapper" id="programs" style="background: #53C6D9;">
  <h1 style="margin-bottom: 86px;">Programs</h1>

  <%= render "page/courses" %>
</div>

<div class="wrapper" id="promos" style="margin-top: 0;  padding-top: 0;" id="about">
  <div class="container page" style="margin-top: 0;">
    <div class="content">
      <h4>PROMOS</h4>
      <div class="col-12 promos">
        <% if @contents.find_by_title('promos') != nil %>
        <%= @markdown.render(@contents.find_by_title('promos').body).html_safe %>
        <% end %>
      </div>
      <br>
      <br>
      <br>
      <br>
      <div style="text-align: center;">
        <a href="http://icancodeclub.com/courses_overview">
          <div style="font-size: 32px;" class="homeButton home">ENROLL IN CLASSES HERE</div>
        </a>
      </div>
    </div>
  </div>
</div>



<hr class="thick">

<div class="wrapper" id="about">
  <div class="container_wide page">
    <h4>LEARN TO CODE</h4>
    <br>
    <br>
        <div class="row">
          <div class="col-5">
            <div class="content">
              <h2>iCanCode Mission</h2>
              <p>
                iCanCode’s mission is to jump-start lower and middle school kids digital literacy and afford our youth in the Rochester community the opportunity to unlock their tech future and learn about computing in a fun digital sandbox.
              </p>


              <h2 style="background-color: #8DE018;">iCanCode Story</h2>
              <p>
                In 2013, my 1st grade son asked me to teach him how to make a game. A few  hours later, he created his first game “Cupcake Eating Gorilla” and became my inspiration to provide younger kids in the Rochester community a fun environment to learn how to code. All technology is governed by code and is the soul of every electronic device our kids interact with, now, not only can they play  games and install apps, they can also learn how to code and make their own!
              </p>
              <h2 style="background: #f271b6;">About the Program</h2>
              <p>
                iCanCode is an after-school community hub for lower and middle school kids Grades 3-10 where they can participate in various computer science based activities using fun aspects of programming and technology tools.  Our curriculum is designed to help students unlock their inner Tech Whiz and develop logical thinking and problem solving skills that last a lifetime                <style>
                  .templinkcolor a{
                      text-decoration: underline;
                      color:#f271b6 !important;
                  }
                .templinkcolor a:visited{
                    color:#f271b6 !important;
                }
                </style>
                <span class="templinkcolor"><%= link_to 'Learn more about our Program Offerings.', courses_overview_path %></span></p>
              </p>

            </div>
          </div>
          <div class="col-5 nomobile wow fadeIn">
            <div class="content">
              <div class="code">
          <pre>
<code class="language-markup" id="editor">
&lt;h1&gt;
    Learn How to Write Code
&lt;/h1&gt;
&lt;div class="wrapper"&gt;
    &lt;p&gt;
        Coding isn't that hard, even kids can learn!
    &lt;/p&gt;
    &lt;div class="row"&gt;
        &lt;h1&gt;
            Kids can Code too!
        &lt;/h1&gt;
        &lt;p&gt;
            It might look challenging,
            but broken down, it's pretty simple.
        &lt;/p&gt;
    &lt;/div&gt;
&lt;/div&gt;
</code>
          </pre>
              </div>
            </div>
          </div>
        </div>
      </div>
</div>







</div>

app/views/page/jcc.html.erb
<div class="lessonPage gameDesign"> <!--used for css rules -->
  <div class="break"></div>
  <div class="container_wide">
    <div class="content">
      <h4>iCanCode Club Camps @ the Jewish Community Center of Rochester</h4>
      <p> 1200 Edgewood Avenue, Rochester NY, 14618 </p>
      <p>
        Grades 3 - 10.  Play, swim, and learn cool 21st-century programming skills 
        and enjoy a great tech experience combined with indoor and outdoor activities.
      </p>
      <p>
        • Interactive Stories and Animations<br>
        • Game Design<br>
        • Javascript<br>
        • Unity<br>
        • Minecraft Modding<br>
        • Web Development<br>
        • Vex Robotics
      </p>
      <p><a style="font-weight: bold;" href="http://jccrochester.org/programs-services/registration/register-online">Click Here to Register</a></p>
    </div>
<br><br><br>
  </div>
</div>