config/routes.rb
Rails.application.routes.draw do

  resources :images

  resources :news

  # set a route to match the hackathon form

  get "/other_events" => redirect("https://docs.google.com/forms/d/1DS7oHuNCYChtcR0WMxuogjYcXEkBCbkeKKf-l4VAfzQ/edit?ts=583e546b"), :as => :other_events
  get "/victor" => redirect("https://icancodeclub.mypaysimple.com/s/icancode-club-school-courses"), :as => :victor
  get "/hackathon" => redirect("https://docs.google.com/forms/d/e/1FAIpQLSd8cA-Oa_p7nbt9TkwZtP7ijqbp5VFgervPen1IqaF1qXox_Q/viewform?c=0&w=1"), :as => :hackathon
  resources :contents
  
  resources :courses

  #resources :students

  devise_for :users

  get 'resources/dragdrop'

  get 'resources/completetag'

  get 'resources/editor'

  post 'resources/download'

  get 'home' => 'page#home'
  get 'jcc' => 'page#jcc'

  get 'curriculum' => 'page#curriculum'

  get 'contact', to: 'messages#new', as: 'contact'
  post 'contact', to: 'messages#create'

  get 'courses_overview' => 'page#courses'

  get 'academic' => 'page#academic'

  get 'camps' => 'page#camps'
  get 'summer' => 'page#summer'
  get 'events' => 'page#events'

  get 'dashboard' => 'dashboard#index'

  get 'admin' => 'dashboard#admin'

  root 'page#home'
end

app/models/class_day.rb
class ClassDay < ActiveRecord::Base
  has_many :students

end

app/models/classtime.rb
class Classtime < ActiveRecord::Base

  TIMES = ['1:00','1:30','2:00','2:30','3:00','3:30','4:00','4:30','5:00','5:30','6:00','6:30','7:00']

  belongs_to :course
  belongs_to :weekday
  has_many :course_students
end

app/models/content.rb
class Content < ActiveRecord::Base
end

app/models/course.rb
class Course < ActiveRecord::Base

  YEARS = []
  6.times do |yearcount|
    YEARS << Time.now.year + yearcount
  end
  #this allows the user to select the year when the course is available.  it looks 6 years into the future for planning purposes.  if nil, the course is offered every year


  monetize :price_cents #allow this column to hold prices

  belongs_to :course_type #difines if class is summer, school, vacation, etc.
  has_many :classtimes #has an array of all possible classtimes

  has_many :students, :through => :course_students #list of students in this course
  has_many :course_students

  accepts_nested_attributes_for :classtimes, :reject_if => :all_blank, :allow_destroy => true

  validates :name, :code, :course_type_id, :presence => true

end

app/models/course_student.rb
class CourseStudent < ActiveRecord::Base
  belongs_to :student
  belongs_to :course
  belongs_to :classtime
end

app/models/course_type.rb
class CourseType < ActiveRecord::Base
  has_many :courses
end

app/models/image.rb
class Image < ActiveRecord::Base
  has_attached_file :file, styles: {large: "1400x"}
  validates_attachment_content_type :file, content_type: /\Aimage\/.*\Z/
end

app/models/message.rb
class Message

  include ActiveModel::Model
  include ActiveModel::Conversion
  include ActiveModel::Validations

  attr_accessor :name, :email, :content, :phone_number, :referral

  validates :name,
            presence: true

  validates :email,
            presence: true

  validates :content,
            presence: true

end

app/models/news.rb
class News < ActiveRecord::Base
end

app/models/student.rb
class Student < ActiveRecord::Base

  GENDERS = ["Male", "Female", "Other"]


  belongs_to :user
  belongs_to :class_day
  belongs_to :class_time

  has_many :courses, :through => :course_students
  has_many :course_students

  has_many :student_parent_informations, :dependent => :destroy
  accepts_nested_attributes_for :student_parent_informations, :allow_destroy => true

  validates :firstname, :lastname, :birthday, :user_id,
      presence: true

  validate :require_parents

  #TODO: validate everything


  #function to set the user

  def set_user!(user)
    self.user_id = user.id
    self.save!
  end

  private

  def require_parents
    errors.add(:base, "You must provide at least one parent.") if student_parent_informations.size < 1 #TODO: validate when deleting with JS
  end


end

app/models/user.rb
class User < ActiveRecord::Base

  attr_accessor :login

  has_many :students

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions.to_h).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    else
      where(conditions.to_h).first
    end
  end

end

app/models/weekday.rb
class Weekday < ActiveRecord::Base
  has_many :classtimes
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  include ApplicationHelper
  before_action :set_course, only: [:show, :edit, :update, :destroy]

  # GET /courses
  # GET /courses.json
  def index
    @courses = Course.where("year >= ? OR year IS NULL", Time.now.year  )
    respond_to do |format|
      format.html
      format.csv { render csv: @courses }
    end
  end

  # GET /courses/1
  # GET /courses/1.json
  def show
  end

  def search
  end

  # GET /courses/new
  def new
    if user_is_admin?
      @course = Course.new
      @course.classtimes.build
    else
      redirect_to root_path
    end
  end

  # GET /courses/1/edit
  def edit
    if !user_is_admin?
      redirect_to root_path
    end
  end

  # POST /courses
  # POST /courses.json
  def create
    if user_is_admin?
      @course = Course.new(course_params)

      respond_to do |format|
        if @course.save
          format.html { redirect_to @course, notice: "#{@course.name} was successfully created." }
          format.json { render :show, status: :created, location: @course }
        else
          format.html { render :new }
          format.json { render json: @course.errors, status: :unprocessable_entity }
        end
      end
    else
      redirect_to root_path
    end
  end

  # PATCH/PUT /courses/1
  # PATCH/PUT /courses/1.json
  def update
    if user_is_admin?
      respond_to do |format|
        if @course.update(course_params)
          format.html { redirect_to @course, notice: "#{@course.name} was successfully updated." }
          format.json { render :show, status: :ok, location: @course }
        else
          format.html { render :edit }
          format.json { render json: @course.errors, status: :unprocessable_entity }
        end
      end
    else
      redirect_to root_path
    end
  end

  # DELETE /courses/1
  # DELETE /courses/1.json
  def destroy
    if user_is_admin?
      @course.destroy
      respond_to do |format|
        format.html { redirect_to courses_url, notice: "#{@course.name} was successfully deleted." }
        format.json { head :no_content }
      end
    else
      redirect_to root_path
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course = Course.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def course_params
      params.require(:course).permit(:name, :code, :description, :duration, :course_type_id, :price, classtimes_attributes: [:id, :start_time, :end_time, :weekday_id, :year, :_destroy])
    end
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/contents_helper.rb
module ContentsHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/news_helper.rb
module NewsHelper

end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/courses/_classtime_fields.html.erb
<fieldset>
  <div class='dtparent'>
    <div class="dangerText remove_fields">
      Delete
    </div>
  </div>

  <div class="field fourth">
    <%= f.label :weekday %>
    <%= f.collection_select(:weekday_id, Weekday.all, :id, :day, class: 'input') %>
  </div>
  <div class="field fourth">
    <%= f.label :start_time %>
    <%= f.select(:start_time, Classtime::TIMES) %>
  </div>
  <div class="field fourth">
    <%= f.label :end_time %>
    <%= f.select(:end_time, Classtime::TIMES) %>
  </div>
  <div class="field fourth">
    <%= f.label :year %>
    <%= f.select(:year, Course::YEARS) %>
  </div>
  <%= f.hidden_field :_destroy %>

</fieldset>

app/views/courses/_form.html.erb
<%= form_for(@course) do |f| %>
    <% if @course.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@course.errors.count, "error") %> prohibited this course from being saved:</h2>
          <ul>
            <% @course.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
    <div class="formContainer">
      <div class="field half">
        <%= f.label :name %><br>
        <%= f.text_field :name, class: 'input' %>
      </div>
      <div class="field half">
        <%= f.label :code %><br>
        <%= f.text_field :code, class: 'input' %>
      </div>
      <div class="field">
        <%= f.label :description %><br>
        <%= f.text_area :description, class: 'input' %>
      </div>
      <div class="field half">
        <%= f.label :duration %><br>
        <%= f.number_field :duration, class: 'input', min: 1, max: 50 %>
      </div>
      <div class="field half">
        <%= f.label :price %><br>
        <%= f.number_field :price, class: 'input', :step => '0.01' %>
      </div>
      <div class="field">
        <%= f.label :course_type %><br>
        <%= f.collection_select(:course_type_id, CourseType.all, :id, :name, class: 'input') %>
      </div>

      <%= f.fields_for :classtimes do |builder| %>
          <%= render 'classtime_fields', f: builder %>
      <% end %>

      <%= link_to_add_fields('Add Classtime', f, :classtimes) %>


    </div>

    <%= f.submit class: "button center formSub sm" %>


<% end %>

app/views/courses/edit.html.erb
<section>
  <div class="container">
    <div class="row">
      <h2>Edit Course</h2>
      <hr class="hrheading">
    </div>

    <%= render 'form' %>

    <%= link_to 'Back', courses_path, class: 'actionButton danger sm' %>
    <%= link_to 'Show', @course, class: 'actionButton warning sm', :target => '_blank' %>
  </div>
</section>

app/views/courses/index.csv.erb
<%- headers = ['Name', 'Code', 'Duration (weeks)', 'Type'] -%>
<%= CSV.generate_line(headers).strip%>

<%- @courses.each do |course| -%>s
    <%- row = [ course.name, course.code, course.duration, course.course_type.name ] -%>
    <%= CSV.generate_line(row).html_safe.strip%>
<%- end -%>

app/views/courses/index.html.erb
<section>
  <div class="container">

    <div class="row">
      <h2>Courses</h2>
      <hr class="hrheading">
    </div>

    <table>
      <thead>
      <tr>
        <th>Name</th>
        <th>Duration</th>
        <th>Type</th>
        <th>Price</th>
        <th colspan="3"></th>
      </tr>
      </thead>

      <tbody>
      <% @courses.each do |course| %>
          <tr>
            <td>
              <%= link_to course do %>
                  <%= course.name %>
              <% end %>
            </td>
            <td><%= course.duration ? "#{course.duration} week#{course.duration > 1 ? "s" : nil}" : nil %></td>
            <td><%= course.course_type.name %></td>
          <td><%= humanized_money_with_symbol course.price %></td>
          <td>
            <%= link_to course do %>
                <div class="actionButton warning sm cen">
                  View
                </div>
            <% end %>
            <% if user_is_admin? %>
                <%= link_to edit_course_path(course) do %>
                    <div class="actionButton warning sm cen">
                      Edit
                    </div>
                <% end %>
                <%= link_to course, method: :delete, data: {confirm: 'Are you sure?'} do %>
                    <div class="actionButton danger sm">
                      Delete
                    </div>
                <% end %>
            <% end %>
          </td>
          </tr>
      <% end %>
      </tbody>
    </table>

    <br>

    <% if user_is_admin? %>

        <%= link_to 'Download', courses_path(:action => :index, :format => :csv), class: 'actionButton warning sm' %>
        <%= link_to 'New Course', new_course_path, class: 'actionButton warning sm' %>

    <% end %>

  </div>
</section>

app/views/courses/new.html.erb
<div class="container">
  <section><div class="row">
    <h2>New Course</h2>
    <hr class="hrheading">
  </div>

  <%= render 'form' %>

  <%= link_to 'Back', courses_path, class: 'actionButton danger sm' %></section>
</div>

app/views/courses/show.html.erb
<div class="container">
  <section>
    <table>
      <caption><%= @course.name %> Information</caption>
      <tr>
        <td>Name
        <td><%= @course.name %></td>
      </tr>
      <tr>
        <td>Code</td>
        <td><%= @course.code %></td>
      </tr>
      <tr>
        <td>Description</td>
        <td><%= @course.description %></td>
      </tr>
      <% if @course.duration %>
          <tr>
            <td>Duration</td>
            <td><%= "#{@course.duration} week#{@course.duration > 1 ? "s" : nil}" %></td>
          </tr>
      <% end %>
      <tr>
        <td>Type</td>
        <td><%= @course.course_type.name %></td>
      </tr>
      <tr>
        <td>Price</td>
        <td><%= humanized_money_with_symbol @course.price %></td>
      </tr>
    </table>


    <% if @course.classtimes.count > 0 %>
        <table>
          <caption>Course Times</caption>
          <% @course.classtimes.each do |classtime| %>
              <tr>
                <td><%= classtime.weekday.day %></td>
                <!--TODO: sort by classtime year, hide times before current year-->
                <td><%= "#{classtime.start_time}" %> <%= classtime.end_time ? "- #{classtime.end_time}" : nil %><%=", #{classtime.year}"%> </td>
              </tr>
          <% end %>
        </table>
    <% end %>

    <div class="break"></div>

    <%= link_to 'Back', courses_path, class: 'actionButton warning sm' %>
    <% if user_is_admin? %>
        <%= ("#{(link_to 'Edit', edit_course_path(@course), class: 'actionButton warning sm')} ").html_safe %>
    <% end %>

  </section>
</div>